version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: comendoria_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: comendoria_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - comendoria_network

volumes:
  db_data:

networks:
  comendoria_network:
    driver: bridge